# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [nogo, block]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username mouse3687
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://shapeshift.io','https://cryptokitties.io','https://catawiki.com','https://opera.com','https://reedsmetal.com','https://loveshriners.org','https://fedex.com','https://O'QUINNTRUCKING.com','https://iab.com','https://abcnews.com','https://nasa.gov','https://juul.com','https://knightlinelegal.com','https://tjhlaw.com/3m', 'https://blockfi.com']
