image: Visual Studio 2017

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  APPVEYOR_BUILD_WORKER_CLOUD: 'GCE'
  matrix:
    - nodejs_version: 10
      test_suite: 'simple'
    - nodejs_version: 10
      test_suite: 'installs'
    - nodejs_version: 10
      test_suite: 'kitchensink'
    - nodejs_version: 10
      test_suite: 'kitchensink-eject'
    - nodejs_version: 8
      test_suite: 'simple'
    - nodejs_version: 8
      test_suite: 'installs'
    - nodejs_version: 8
      test_suite: 'kitchensink'
    - nodejs_version: 8
      test_suite: 'kitchensink-eject'
  access_token:
    secure: # <your token here>
  github_email:
    secure: # <your email here>

cache:
  - '%APPDATA%\npm-cache -> appveyor.cleanup-cache.txt'
  - '%LOCALAPPDATA%\Yarn\Cache -> appveyor.cleanup-cache.txt'

clone_depth: 50

matrix:
  fast_finish: true
  allow_failures:
    - test_suite: 'installs'

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: |
      (New-Object Net.WebClient).DownloadFile("https://nightly.yarnpkg.com/latest.msi", "$env:temp\yarn.msi")
      cmd /c start /wait msiexec.exe /i $env:temp\yarn.msi /quiet /qn /norestart

build: off

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn cache dir
  - bash tasks/e2e-%test_suite%.sh

deploy_script:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email %github_email%
  - git config --global user.name # <your name here> e.g. "IlyaFinkelshteyn"
  - git subtree push --prefix website origin gh-pages