#
# GitHub Actions configuration for building and testing create-react-app on Linux, Windows, and macOS.
#

name: E2E (end to end) Tests

on:
  push:
    branches:
      - main

env:
  # Sets TEMP to be on the same drive as the cloned source on Windows. This avoids test scripts that "cd" into a directory under TEMP from failing because this directory is on a different drive from the current directory.
  VSTS_OVERWRITE_TEMP: True
  CRA_INTERNAL_TEST: true

# ******************************************************************************
# Simple test suite
# ******************************************************************************
jobs:
  simple:
    uses: ./test-job.yml
    with:
      name: Simple
      testScript: tasks/e2e-simple.sh

  # ******************************************************************************
  # Installs test suite
  # ******************************************************************************
  installs:
    uses: ./test-job.yml
    with:
      name: Installs
      testScript: tasks/e2e-installs.sh

  # ******************************************************************************
  # Kitchensink test suite
  # ******************************************************************************
  kitchensink:
    uses: ./test-job.yml
    with:
      name: Kitchensink
      testScript: tasks/e2e-kitchensink.sh

  # ******************************************************************************
  # Kitchensink Eject test suite
  # ******************************************************************************
  # - template: azure-pipelines-test-job.yml
  #   parameters:
  #     name: KitchensinkEject
  #     testScript: tasks/e2e-kitchensink-eject.sh

  # ******************************************************************************
  # Behavior test suite
  # ******************************************************************************
  # - template: azure-pipelines-test-job.yml
  #   parameters:
  #     name: Behavior
  #     testScript: tasks/e2e-behavior.sh
  #     configurations:
  #       LinuxNode14: { vmImage: 'ubuntu-latest', nodeVersion: 14.x }
  #       LinuxNode16: { vmImage: 'ubuntu-latest', nodeVersion: 16.x }
  #       WindowsNode14: { vmImage: 'windows-2019', nodeVersion: 14.x }
  #       WindowsNode16: { vmImage: 'windows-2019', nodeVersion: 16.x }
  #       MacNode14: { vmImage: 'macOS-10.15', nodeVersion: 14.x }
  #       MacNode16: { vmImage: 'macOS-10.15', nodeVersion: 16.x }

  # ******************************************************************************
  # Old Node test suite
  # ******************************************************************************
  oldnode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 8
          cache: 'npm'
        name: 'Install Node.js 8.x'
      - run: tasks/e2e-old-node.sh
        name: 'Run tests'
