name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install npm@8
        run: npm i -g npm@8
      - name: Install yarn
        run: npm i -g yarn
      - name: Install packages
        run: npm ci --prefer-offline
      - name: Run integration tests
        run: npm run test:integration
